### ISSUE TITLE
Fail build android

### ISSUE THREAD

**Issue by zeptoZB** [Wizcorp/cordova-plugin-webviewselector#3]
Line 14 in plugin.xml:
&lt;uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18"/&gt;

It conflicts with the same permission without the android SDK version of another plugin.
Solution was remove version dependency in plugin.xml...

&lt;uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /&gt;

**Comment by tbrebant** [comment]
It makes sense: our plugin only needs this permission on Android 4.3 or less (following versions are allowing an application to write in its own application-specific directories without this permission) and the less permissions you ask to your user, better it is.

So if another plugin does not have this particularity and needs this permission on all versions of Android, I can understand the conflict between declarations.

On the other hand, I don't know why Cordova did not merged smartly by keeping only the larger scope. I don't know if he's able to do that. I'll keep the issue open until we investigate.

**Comment by zeptoZB** [comment]
You're correct in your assertions, but unfortunately Cordova does not properly merge this situation, leading to compile error by duplicity of permission. Correct would be to fix the Cordova, but this is out of my reach.

**Comment by tbrebant** [comment]
Understood, I will add something about that in the documentation.

Not related to the issue: I'm curious, what version of Cordova CLI and Android engine are you using? If they are more recent than what we mentioned in the ReadMe (Cordova 6.5.0 and Android engine 4.1.1) and is working well I would be happy to know.

**Comment by zeptoZB** [comment]
Sorry for the delay...
Ionic 3.13.0
Cordova 7.1.0
Android SDK Tools 25.2.5
Android SDK Platform-tools 26.0.1
Android SDK Build-tools 26.0.2
Android 7.1.1 (API 25) SDK Platform 25.3

**Comment by aluferraz** [comment]
same error here..

**Comment by aluferraz** [comment]
I think that for a better compatibility it would be better to leave the dependency without the minSdkVersion spec.

I will fork your repo in order to do that and use your plugin :), but please consider...

**Comment by tbrebant** [comment]
Hi. I just merged the PR mentioning the potential conflict and how to solve it in the documentation.

I would not like this plugin to request more permissions than what is required so I prefer to keep the version cap.

**Comment by aluferraz** [comment]
Thanks !!! And congrats, it is a great plugin !
